package centigrade;

public enum Genre {
    DRAMA, MUSICAL, ROMANCE, FAMILY, WAR, CRIME,
    THRILLER, ACTION, ADVENTURE, COMEDY, HISTORY,
    BIOGRAPHY, MYSTERY, DOCUMENTARY, SHORT, SPORT,
    WESTERN, FANTASY, SCI_FI, HORROR, ADULT, ANIMATION,
    MUSIC, FILM_NOIR, NEWS, FOOD, REALITY, CHILDREN, GAME_SHOW, TRAVEL,
    MINI_SERIES, HOME_AND_GARDEN, SOAP, TALK, SUSPENSE
}
